name: Sync Fork with Upstream

on:
  schedule:
    - cron: '*/10 * * * *' # Every 10 minutes

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - name: Sync and merge upstream repository with your current repository
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with:
          upstream_repo: https://github.com/Kampus-Merdeka-Software-Engineering/km-feb24-balikpapan-17.git
          
          upstream_branch: main
          
          downstream_branch: main
          
          token: ${{ secrets.GITHUB_TOKEN }}
    
              
